### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by colinkiama** [vanat/vanat#15]
Are there plans for adding a roadmap of features to implement and issues to fix?

I can see areas in the code that haven't been implemented yet but I'm unsure whether it's possible to start on them, if you are currently working on them or if it should even be prioritised.

**Comment by devnix** [comment]
I would say:

- [ ] JSON schema for packages, and repositories
- [ ] Dependency tree resolution, I guess it should be able to download dependencies recursively, detect conflicts, and try to get the latest compatible version of each possible package (or the lowest one if specified)
- [ ] Ability to add repositories and abstract package download, to add a vcs supporting Git at least (see https://getcomposer.org/doc/05-repositories.md)
- [ ] I think the version parameter is not implemented on package download. It's going to look into tags? Should it work with commit hashes?

WDYT?

**Comment by ckmercantile** [comment]
I think all these are great but I'm not sure if continuing work on this repo is the best option. The maintainers seems like they are busy right now.

I feel like we can get these features done much faster with more active maintainers.

**Comment by colinkiama** [comment]
I think that this list is great but it's best to continue the development of the package manager in another repo or even start over. The current maintainers seem super busy right now.

I think that in a repo with more active maintainers, the features can be implemented much faster and it would have better documentation across the board.

**Comment by robertsanseries** [comment]
@colinkiama work and other projects leave me almost out of time!

I'm trying to resolve issues #3 and #4. However I couldn't get json-glib-1.0.vapi to work in the project. Branch **Develop**

I will organize the kanban board.

**Comment by robertsanseries** [comment]
@devnix @colinkiama kanban board created: https://github.com/vanat/vanat/projects/3

I'll open other issues with what I want to implement too and add to the board. My vision is that the project works according to Composer.
